chore: enable JWPlayer's Chromecast support
applicaster/zapp-player-plugin-jw pull request #12
Opened 2020-01-24 21:11 UTC by Taxxodium

## Description

- added configuration to enable Chromecast to JWPlayer
- added necessary UI changes to JWPlayer
- version bump

## Known issues

## Checklist

* [X] PR is scoped to one task
* [ ] Tests are included
* [ ] Documentation is included

* [ ] This PR is not making any UI change
* [X] This PR is making a UI change
  * [X] Screenshot(s) included

![Simulator Screen Shot - iPhone 11 - 2020-01-24 at 14 56 51](https://user-images.githubusercontent.com/157116/73104311-be41a100-3ebb-11ea-9d09-c1c3f4dea82a.png)

## QA :

* required test cases:
* specific apps / plugins to test :

2020-01-24 21:23 UTC, snooky23 requested changes
Hi, your implementation doesn't implement the base requirements of Chromecast behavior. 
1. See notes about ios 13 - https://developers.google.com/cast/docs/ios_sender/ios13_changes
2. Did you tested all Google Cast Design Checklist which can be found [here](https://developers.google.com/cast/docs/design_checklist)
3. Why are you not referring to the ZappConnector Chromecast delegate and use what we already built in the generic plugin?

Please go over the above and schedule a meeting to approve it.

2020-01-24 21:23 UTC, snooky23 commented on Specs/JWPlayerPlugin/3.3.3/JWPlayerPlugin.podspec
> +  s.dependency 'google-cast-sdk-no-bluetooth'
Please work with the same cast version we are using for the generic ios plugin

2020-01-24 21:23 UTC, snooky23 commented on iOS/JWPlayerPlugin.podspec
> +  s.dependency 'google-cast-sdk-no-bluetooth'
Please work with the same cast version we are using for the generic ios plugin

2020-01-24 21:23 UTC, snooky23 commented on iOS/Podfile
> +  pod 'google-cast-sdk-no-bluetooth'
Please work with the same cast version we are using for the generic ios plugin

2020-01-24 21:35 UTC, Taxxodium commented
> Hi, your implementation doesn't implement the base requirements of Chromecast behavior.
> 
> 1. See notes about ios 13 - https://developers.google.com/cast/docs/ios_sender/ios13_changes

We need to define if we are going to use guest mode or not. Currently I'm using the non guest mode, but we need to discuss this.

> 2. Did you tested all Google Cast Design Checklist which can be found [here](https://developers.google.com/cast/docs/design_checklist)

JWPlayer already has support for Chromecast. From what I could see of their implementation they do comply to that checklist. But we will need to do some QA to be sure.

> 3. Why are you not referring to the ZappConnector Chromecast delegate and use what we already built in the generic plugin?

We are using JWPlayer's implementation. Just like we did with Airplay, we did not write Airplay from scratch, just enabled or disabled it in JWPlayer. Same with Chromecast.
The only thing that we do "extra" is add a button as in the screenshot above.

2020-03-04 13:09 UTC, rkarpievich-sc approved these changes

2020-03-09 14:13 UTC, closed without merging